qiniu:
  switch: false
  accessKey: "yourAccessKey"
  secretKey: "yourSecretKey"
  bucket: "yourBucketName"
  useHTTPS: false                       #是否使用https域名
  UseCdnDomains: false                  #上传是否使用CDN上传加速
  upTokenExpires: 7200                  #上传凭证2小时有效期
  callbackURL: ""                       #上传回调地址
  callbackBodyType: "application/json"  #上传回调信息格式
  endUser: ""                           #唯一宿主标识
  fsizeMin: 1024                        #限定上传文件大小最小值，单位Byte。
  fsizeLimit: 10485760                  #限定上传文件大小最大值，单位Byte。超过限制上传文件大小的最大值会被判为上传失败，返回 413 状态码。
  mimeLimit: "image/jpeg;image/png;image/gif"  #限定上传类型
aliyun:
  switch: false
  accessKeyId: "yourAccessKeyId"
  accessKeySecret: "yourAccessKeySecret"
  bucketName: "yourBucketName"
  endpoint: "http://oss-cn-shenzhen.aliyuncs.com" #CDN空间机房
  useCname: false             #是否使用自定义域名CNAME
  connTimeout:  10            #请求超时时间，包括连接超时、Socket读写超时，单位秒,默认连接超时30秒，读写超时60秒
  rwTimeout: 120
  securityToken: ""           #临时用户的SecurityToken
  enableMD5: false            #是否开启MD5校验。推荐使用CRC校验，CRC的效率高于MD5
  enableCRC: true             #是否开启CRC校验
  proxy: ""                   #代理服务器，如http://8.8.8.8:3128
  authProxy: ""               #带账号密码的代理服务器

